[package]
name = "xpd-util"
version = "0.1.0"
edition = "2024"

[dependencies]
twilight-cache-inmemory = { version = "0.17", features = ["permission-calculator"] }
twilight-model = "0.16"

xpd-common = { workspace = true }

# error handling
thiserror = "2"
tracing = "0.1"