[package]
name = "anvil-listener"
version = "0.1.0"
edition = "2021"
authors = ["valkyrie_pilot <valk@randomairborne.dev>"]
description = "A websocket listener for anvil"
repository = "https://github.com/randomairborne/anvil"
readme = "README.txt"
license = "MS-PL"
categories = ["games"]
keywords = ["discord-bot", "mee6"]

[dependencies]
futures = "0.3"
dashmap = "5.4"
rand = "0.8"
dotenvy = "0.15"
twilight-model = "0.13"
twilight-http = "0.13"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
twilight-gateway = "0.13"
sqlx = { version = "0.6", features = ["runtime-tokio-rustls", "tls", "mysql", "macros"] }
mee6 = "0.0.2"
