[package]
name = "xpd-slash-defs"
version = "0.1.0"
edition = "2024"

[dependencies]
twilight-interactions = "0.17"
twilight-validate = "0.17"
twilight-model = "0.17"

xpd-rank-card = { workspace = true }
xpd-common = { workspace = true }
