[package]
name = "xpd-setcommands"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["rt", "macros"] }

xpd-slash-defs = { workspace = true }

twilight-http = "0.16.0"
twilight-model = "0.16.0"

valk-utils = "0.1"